name: redvsblue
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Navigation
  go_router: ^13.2.5

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5

  # Authentication
  google_sign_in: ^6.3.0

  # Network
  dio: ^5.7.0
  dio_web_adapter: ^2.0.0

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3

  # UI Components
  flutter_animate: ^4.5.0
  cached_network_image: ^3.4.0
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.3.2

  # Location
  geolocator: ^10.1.1

  # Charts
  fl_chart: ^0.64.0

  # Utilities
  intl: ^0.19.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  equatable: ^2.0.7

  # Other
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

  # Code Generation
  build_runner: ^2.4.14
  freezed: ^2.5.8
  json_serializable: ^6.9.5
  riverpod_generator: ^2.6.2

flutter:
  uses-material-design: true

  # Assets configuration
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
    - assets/fonts/

  # Font configuration (if you have custom fonts)
  # fonts:
  #   - family: CustomFont
  #     fonts:
  #       - asset: assets/fonts/CustomFont-Regular.ttf
  #       - asset: assets/fonts/CustomFont-Bold.ttf
  #         weight: 700